name: photo_app
description: Algebra project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.1
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  retrofit: ^3.3.1
  dio: ^4.0.6
  control_style: ^0.0.3
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.7
  dartz: ^0.10.1
  google_sign_in: ^5.4.2
  persistent_bottom_nav_bar_v2: ^4.2.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  image_picker: ^0.8.6
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1
  mockito: ^5.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf